apiVersion: v1
entries:
  demoliberty:
  - created: 2018-06-18T08:24:15.709339+02:00
    description: Simple Liberty Demo
    digest: c4157b138e6860f71985872fa21a8396c7c4eedf3dcd4bc5c04e2b86f64064fa
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.3.0.tgz
    version: 1.3.0
  - created: 2018-06-18T08:24:15.708981+02:00
    description: Simple Liberty Demo
    digest: 28a25f8dc1feb129ae441beabb8186542ed58c60d051b7b83183dc4b8c459c24
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.2.0.tgz
    version: 1.2.0
  - created: 2018-06-18T08:24:15.708631+02:00
    description: Simple Liberty Demo
    digest: 4394f94977c53150974d2ab5ebd6b704d144fe826844c81b305bfa5fc1c677e3
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.1.0.tgz
    version: 1.1.0
  - created: 2018-06-18T08:24:15.708227+02:00
    description: Simple Liberty Demo
    digest: 626229259bd4c423d8de43077396676c27e342f95389d0290ed0b12063a7be43
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.0.0.tgz
    version: 1.0.0
generated: 2018-06-18T08:24:15.707629+02:00
