apiVersion: v1
entries:
  demoliberty:
  - created: 2018-06-18T08:38:25.469665+02:00
    description: Simple Liberty Demo
    digest: 24ceeb8bb053e3f6fa2fce5641941f41b6db73e98d42f80ae24f25bbb02f1709
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.3.0.tgz
    version: 1.3.0
  - created: 2018-06-18T08:38:25.46918+02:00
    description: Simple Liberty Demo
    digest: 8af6708c1b2aca56d910eb80ca79df6ffe95465f857a916cb275d9b8c4452011
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.2.0.tgz
    version: 1.2.0
  - created: 2018-06-18T08:38:25.468633+02:00
    description: Simple Liberty Demo
    digest: 4df79856bf7bb713d1890f5a09791ac9b52ba7198bff85afd488aa547c0a9d0b
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.1.0.tgz
    version: 1.1.0
  - created: 2018-06-18T08:38:25.468172+02:00
    description: Simple Liberty Demo
    digest: 2aea03104000972d22e812878d1885698e936f1286a720a70a3c8f3d80ed0574
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/demoliberty/master/charts/stable/repo/stable/demoliberty-1.0.0.tgz
    version: 1.0.0
generated: 2018-06-18T08:38:25.467488+02:00
